

List<String> getLyrics() {

  return [
'[Verse 1] You’re bigger than the universe',
'You’re bigger than the sun and the stars',
'Your bigger than the things',
'That can tell me your heart',
'You’re bigger than the universe',
'You’re bigger than the sun and the stars',
'Your bigger than the things oh my oh my',
'That can tell your heart',
'For I know',
'You’re brave',
'For I know',
'You’re brave'
'You’re bigger',
'You’re bigger than the problems I face'
'You’re bigger than the disaster I seen',
'You’re bigger',

'Your so much bigger Jesus',
'Than what this life may bring',
'You’re bigger than the universe',
'You’re bigger than the sun and the stars',
'Your bigger than the things',
'Bigger than the things',
'That can tell your heart',
'For I know',
'You’re brave',
'For I know',
'You’re brave',
'That can tell your heart',
'For I know',
'You’re brave',
'For I know',
'You’re brave',

'You’re bigger bigger bigger bigger you’re bigger Jesus',
'Bigger sing',
'Bigger',
'Bigger',
'You’re bigger yes you are',
'You’re bigger Jesus',
'You’re bigger',
'You’re bigger than any [?] of a problem',
'You’re bigger',
'You’re bigger than any broken home',
'You’re bigger',
'You’re bigger than life Jesus',
'You’re bigger',
'You’re even bigger than negativity',
'You’re bigger',
'Oh you’re bigger you’re bigger yes you are',
'You’re bigger',
'Bigger than H.I.V',

'Bigger than cancer Jesus',
'You’re bigger than diabetes',
'The strong soul your back makes you bigger',
'The strong soul your back they make you bigger',
'They make you bigger',
'Your blood makes you bigger',
'Your love makes you bigger',
'You overcame death',
'And that makes you bigger',
'That makes you bigger',
'You oughta open up your mouth right here and make [?] tonight',
'You’re bigger yes you are'];
}